elfin_arm_controller: # controller name
  type: position_controllers/JointTrajectoryController # controller type
  joints: # joint names
     - elfin_joint1
     - elfin_joint2
     - elfin_joint3
     - elfin_joint4
     - elfin_joint5
     - elfin_joint6
  constraints: # joint limits
      goal_time: 0.6 # s
      stopped_velocity_tolerance: 0.1 # rad/s

  stop_trajectory_duration: 0.05 # s
  state_publish_rate:  25 # Hz
  action_monitor_rate: 10 # Hz
